version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/App"
    schedule:
      interval: "weekly"
      
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/Backend"
    schedule:
      interval: "weekly"
